name: Detect Push in Specific Repo

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le repo et exécuter le bon pipeline
        run: |
          REPO_NAME="${{ github.repository }}"
          echo "Push détecté sur: $REPO_NAME"

          if [[ "$REPO_NAME" == "organisation-tes/yassin-nodejs" ]]; then
            WORKFLOW="ci-nodejs.yml"
          else
            echo "Aucun pipeline défini pour ce repo."
            exit 1
          fi

          echo "Lancement de $WORKFLOW..."
          curl -X POST -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/organisation-tes/ci-template/actions/workflows/$WORKFLOW/dispatches \
               -d '{"ref": "main"}'
