name: Detect New Repo

on:
  repository_dispatch:
    types: [new-repo]

jobs:
  detect-language:
    runs-on: ubuntu-latest
    steps:
      - name: Extraire le type de projet
        run: |
          REPO_NAME="${{ github.event.client_payload.repository }}"
          echo "Repository détecté: $REPO_NAME"

          # Détection du langage basé sur le nom du repo
          if [[ "$REPO_NAME" == *"-nodejs" ]]; then
            WORKFLOW="ci-nodejs.yml"
          elif [[ "$REPO_NAME" == *"-java" ]]; then
            WORKFLOW="ci-java.yml"
          elif [[ "$REPO_NAME" == *"-python" ]]; then
            WORKFLOW="ci-python.yml"
          else
            echo "Aucun pipeline trouvé pour ce type de projet."
            exit 1
          fi

          echo "Workflow à exécuter: $WORKFLOW"
          echo "WORKFLOW=$WORKFLOW" >> $GITHUB_ENV

      - name: Déclencher le workflow correspondant
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               https://api.github.com/repos/organisation-tes/ci-template/actions/workflows/$WORKFLOW/dispatches \
               -d '{"ref": "main"}'
