name: Detect New Repo
on:
  repository_dispatch:
    types: [new-repo]

jobs:
  handle-new-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le dépôt créé
        run: echo "Un nouveau dépôt a été créé : ${{ github.event.client_payload.repository }}"

      - name: Exécuter une action personnalisée
        run: |
          echo "Tu peux ajouter ici des actions, comme cloner le repo, lancer un script, etc."
