name: Detect New Repo

on:
  repository_dispatch:
    types: [new-repo]

jobs:
  trigger-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Extraire le nom du repo
        run: |
          REPO_NAME="${{ github.event.client_payload.repository }}"
          echo "Repository créé: $REPO_NAME"
          
          if [[ "$REPO_NAME" == *"-nodejs" ]]; then
            echo "Déclenchement de ci-nodejs.yml"
            gh workflow run ci-nodejs.yml -R mon-org/$REPO_NAME
          elif [[ "$REPO_NAME" == *"-java" ]]; then
            echo "Déclenchement de ci-java.yml"
            gh workflow run ci-java.yml -R mon-org/$REPO_NAME
          else
            echo "Aucun pipeline correspondant"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
